icon_mapping = {
    200: 'weather_icons/animated/scattered-thunderstorms',
    201: 'weather_icons/animated/scattered-thunderstorms',
    202: 'weather_icons/animated/scattered-thunderstorms',
    210: 'weather_icons/animated/scattered-thunderstorms',
    211: 'weather_icons/animated/scattered-thunderstorms',
    212: 'weather_icons/animated/scattered-thunderstorms',
    221: 'weather_icons/animated/scattered-thunderstorms',
    230: 'weather_icons/animated/scattered-thunderstorms',
    231: 'weather_icons/animated/scattered-thunderstorms',
    232: 'weather_icons/animated/scattered-thunderstorms',
    
    300: 'weather_icons/animated/rainy-1',
    301: 'weather_icons/animated/rainy-1',
    302: 'weather_icons/animated/rainy-2',
    310: 'weather_icons/animated/rainy-1',
    311: 'weather_icons/animated/rainy-1',
    312: 'weather_icons/animated/rainy-2',
    313: 'weather_icons/animated/rainy-1',
    314: 'weather_icons/animated/rainy-2',
    321: 'weather_icons/animated/rainy-1',

    500: 'weather_icons/animated/rainy-2',
    501: 'weather_icons/animated/rainy-2',
    502: 'weather_icons/animated/rainy-3',
    503: 'weather_icons/animated/rainy-3',
    504: 'weather_icons/animated/rainy-3',
    511: 'weather_icons/animated/rainy-2',
    520: 'weather_icons/animated/rainy-2',
    521: 'weather_icons/animated/rainy-2',
    522: 'weather_icons/animated/rainy-3',
    531: 'weather_icons/animated/rainy-2',

    600: 'weather_icons/animated/snowy-1',
    601: 'weather_icons/animated/snowy-2',
    602: 'weather_icons/animated/snowy-3',
    611: 'weather_icons/animated/rain-and-sleet-mix',
    612: 'weather_icons/animated/rain-and-sleet-mix',
    613: 'weather_icons/animated/rain-and-sleet-mix',
    615: 'weather_icons/animated/rain-and-snow-mix',
    616: 'weather_icons/animated/rain-and-snow-mix',
    620: 'weather_icons/animated/rain-and-snow-mix',
    621: 'weather_icons/animated/rain-and-snow-mix',
    622: 'weather_icons/animated/rain-and-snow-mix',

    701: 'weather_icons/animated/fog',
    711: 'weather_icons/animated/fog',
    721: 'weather_icons/animated/haze',
    731: 'weather_icons/animated/dust',
    741: 'weather_icons/animated/fog',
    751: 'weather_icons/animated/dust',
    761: 'weather_icons/animated/dust',
    762: 'weather_icons/animated/haze',
    771: 'weather_icons/animated/wind',
    781: 'weather_icons/animated/tornado',
    800: 'weather_icons/animated/clear',

    801: 'weather_icons/animated/cloudy-1',
    802: 'weather_icons/animated/cloudy-2',
    803: 'weather_icons/animated/cloudy-3',
    804: 'weather_icons/animated/cloudy-3',
}